# train, test split

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import random

In [2]:
df = pd.read_csv('/home/sd3528/hetav-2/data/2700_comments_final_labeled.csv')

In [3]:
df

,Serial_Number,id,text,label,llm_model,Label_Topic
0,1456,UgwijHsLdRqfG3pZgzl4AaABAg,:face_with_tears_of_joy::face_with_tears_of_joy:,6,llama3:70b,Irrelevant/General Comments
1,789,UgzB2u4M8XnMBncOmpl4AaABAg,His parents should be jailed for this,5,llama3:70b,Anger or Outrage
2,356,UgzvrOYpFFrvlvxA2bN4AaABAg,This pain is beyond imagination.. I've gone th...,5,llama3:70b,Anger or Outrage
3,339,UgwLGexOGBQH8NM_nuh4AaABAg,"Hammurabi‚Äôs Code, often hailed as the first ...",3,llama3:70b,Socioeconomic Privilege
4,3142,UgwMoq3JUHoPRLLHeH94AaABAg,#justicefortheemplyee,6,llama3:70b,Irrelevant/General Comments
...,...,...,...,...,...,...
2702,2515,Ugy6jRuTrKk514u6N2Z4AaABAg,Where is our PM in all this? Modi bhai? Alive?,5,llama3:70b,Anger or Outrage
2703,2348,UgzTIrQ-FtAWrbnRIil4AaABAg,I need to know today's Juvenile Justice Act ca...,5,llama3:70b,Anger or Outrage
2704,1609,UgxfME6X-E8x_ZNXVBZ4AaABAg,Builders have no respect for people money... t...,5,llama3:70b,Anger or Outrage
2705,2542,Ugy4jhkIWb5wFJoFWO54AaABAg,Doc/judge reserved category se hai. Reservatio...,5,llama3:70b,Anger or Outrage
2706,2576,UgyvY06TAEO-AWLMRsV4AaABAg,Shame on Indian Judiciary,5,llama3:70b,Anger or Outrage

In [4]:
df['label'].value_counts()

label
6    1065
5     715
7     266
3     231
1     231
4     141
2      58
Name: count, dtype: int64

In [5]:
df['label'] = df['label'].apply(lambda x: x-1)

In [6]:
df['label'].value_counts()

label
5    1065
4     715
6     266
2     231
0     231
3     141
1      58
Name: count, dtype: int64

In [7]:
df = df.sample(frac=1).reset_index(drop=True)

In [9]:
df = df[['text', 'label']]

In [10]:
df_train = df[:int(len(df)*0.8)]
df_test = df[int(len(df)*0.8):]

df_valid = df_test[:int(len(df_test)*0.5)]
df_test = df_test[int(len(df_test)*0.5):]

In [11]:
df

                                                   text  label
0     Uska paas bahuth paisa hei,washingmachine khar...      5
1     Sir one video on salman khan car accident kill...      6
2     Insurance only 25% logon ko hi milta hai. Insu...      4
3     Then how come Salman Khan is roaming free, wha...      6
4     People keep honking from behind because I stay...      1
...                                                 ...    ...
2702                                   We want justice.      3
2703  Isme MLA @Ravindra Dhangekar ko Thank you boln...      5
2704            Justice for neet aspirant :crying_face:      6
2705  That's the reason logo ko matter hath Mai Lena...      4
2706  Middle class walo ki koi sunta bhi ni :crying_...      4

[2707 rows x 2 columns]

In [12]:
df_train.to_csv('/home/sd3528/hetav-2/data/train.csv', index=False)
df_test.to_csv('/home/sd3528/hetav-2/data/test.csv', index=False)
df_valid.to_csv('/home/sd3528/hetav-2/data/valid.csv', index=False)

In [29]:
import pandas as pd
df_majority = pd.read_csv('/home/sd3528/hetav-2/data/top_100_majority_human_annotate_corrected.csv')
df_labelled = pd.read_csv('/home/sd3528/hetav-2/data/2700_comments_final_labeled.csv')

In [30]:
df_majority

,id,text,human_label
0,0933ba35-b3ee-4dd3-8309-c4bd0d128666,Em clear ga cheppav :party_popper:nice :thumbs...,6
1,a75b4d0d-a089-478f-a615-432109ffafaa,Paisa is sab hai ... Our system is totally cor...,5
2,461c8dd7-449f-4789-a3a2-67a3efd72074,We want justice.....the value of their lives z...,4
3,267daf2c-7cde-4b0d-8688-b8fa1d0bed55,I lived in ahmednagar.. And i found that u nee...,2
4,67e905d8-2823-4241-b1fd-7b88e677a4a9,"You always covered the news really well ,comm...",6
...,...,...,...
695,bb3731f5-977b-43e8-9cc4-39c94e61c6a4,I am from Indore and I don’t hesitate to accep...,2
696,27694197-80f1-4cf4-8f9d-de4cc336f789,Indian judiciary system fucked up....I persona...,1
697,80f9e4ea-773d-46be-9779-6f9699b5b1d0,Money is everything in India. You have money a...,3
698,5bc925eb-3ebb-4081-ab1e-e7ba41937fb9,Nothing changed in 10 years .people are being ...,2
699,1f95a3ad-258f-4187-8791-cb1fbd12f5e2,Justice for both of them and my condolences om...,4

In [31]:
df_majority['human_label'] = df_majority['human_label'].apply(lambda x: x-1)
df_majority['human_label'].value_counts()

human_label
4    133
5    123
0    106
2    100
6     98
3     93
1     47
Name: count, dtype: int64

In [32]:
df_labelled

,Serial_Number,id,text,label,llm_model,Label_Topic
0,1456,UgwijHsLdRqfG3pZgzl4AaABAg,:face_with_tears_of_joy::face_with_tears_of_joy:,6,llama3:70b,Irrelevant/General Comments
1,789,UgzB2u4M8XnMBncOmpl4AaABAg,His parents should be jailed for this,5,llama3:70b,Anger or Outrage
2,356,UgzvrOYpFFrvlvxA2bN4AaABAg,This pain is beyond imagination.. I've gone th...,5,llama3:70b,Anger or Outrage
3,339,UgwLGexOGBQH8NM_nuh4AaABAg,"Hammurabi‚Äôs Code, often hailed as the first ...",3,llama3:70b,Socioeconomic Privilege
4,3142,UgwMoq3JUHoPRLLHeH94AaABAg,#justicefortheemplyee,6,llama3:70b,Irrelevant/General Comments
...,...,...,...,...,...,...
2702,2515,Ugy6jRuTrKk514u6N2Z4AaABAg,Where is our PM in all this? Modi bhai? Alive?,5,llama3:70b,Anger or Outrage
2703,2348,UgzTIrQ-FtAWrbnRIil4AaABAg,I need to know today's Juvenile Justice Act ca...,5,llama3:70b,Anger or Outrage
2704,1609,UgxfME6X-E8x_ZNXVBZ4AaABAg,Builders have no respect for people money... t...,5,llama3:70b,Anger or Outrage
2705,2542,Ugy4jhkIWb5wFJoFWO54AaABAg,Doc/judge reserved category se hai. Reservatio...,5,llama3:70b,Anger or Outrage
2706,2576,UgyvY06TAEO-AWLMRsV4AaABAg,Shame on Indian Judiciary,5,llama3:70b,Anger or Outrage

In [33]:
df_labelled['label'] = df_labelled['label'].apply(lambda x: x-1)
df_labelled['label'].value_counts()

label
5    1065
4     715
6     266
2     231
0     231
3     141
1      58
Name: count, dtype: int64

In [34]:
df_dict = []
for i in range(len(df_majority)):
  df_dict.append({
    'text': df_majority['text'][i],
    'label': df_majority['human_label'][i]
  })
  
for i in range(len(df_labelled)):
  df_dict.append({
    'text': df_labelled['text'][i],
    'label': df_labelled['label'][i]
  })
  
df_majority_sampling = pd.DataFrame(df_dict)
df_majority_sampling

                                                   text  label
0     Em clear ga cheppav :party_popper:nice :thumbs...      5
1     Paisa is sab hai ... Our system is totally cor...      4
2     We want justice.....the value of their lives z...      3
3     I lived in ahmednagar.. And i found that u nee...      1
4     You always covered the news really well  ,comm...      5
...                                                 ...    ...
3402     Where is our PM in all this? Modi bhai? Alive?      4
3403  I need to know today's Juvenile Justice Act ca...      4
3404  Builders have no respect for people money... t...      4
3405  Doc/judge reserved category se hai. Reservatio...      4
3406                          Shame on Indian Judiciary      4

[3407 rows x 2 columns]

In [35]:
# train test split
df_majority_sampling = df_majority_sampling.sample(frac=1).reset_index(drop=True)
df_majority_sampling_train = df_majority_sampling[:int(len(df_majority_sampling)*0.8)]
df_majority_sampling_test = df_majority_sampling[int(len(df_majority_sampling)*0.8):]

df_majority_sampling_valid = df_majority_sampling_test[:int(len(df_majority_sampling_test)*0.5)]
df_majority_sampling_test = df_majority_sampling_test[int(len(df_majority_sampling_test)*0.5):]

len(df_majority_sampling_train), len(df_majority_sampling_test), len(df_majority_sampling_valid)

(2725, 341, 341)

In [36]:
assert (df_majority_sampling_test.iloc[0] != df_majority_sampling_valid.iloc[0]).all()

In [37]:
import os
os.makedirs('/home/sd3528/hetav-2/data/majority-sampling', exist_ok=True)
df_majority_sampling_train.to_csv('/home/sd3528/hetav-2/data/majority-sampling/train_majority_sampling.csv', index=False)
df_majority_sampling_test.to_csv('/home/sd3528/hetav-2/data/majority-sampling/test_majority_sampling.csv', index=False)
df_majority_sampling_valid.to_csv('/home/sd3528/hetav-2/data/majority-sampling/valid_majority_sampling.csv', index=False)